//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Action/ActionControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ActionControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ActionControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ActionControl"",
    ""maps"": [
        {
            ""name"": ""ClickAction"",
            ""id"": ""da6c30d1-972d-4ba2-9871-23c675552815"",
            ""actions"": [
                {
                    ""name"": ""Mouse_Left"",
                    ""type"": ""Button"",
                    ""id"": ""aab923d3-f35f-47a6-a0ce-a69259214274"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mouse_Position"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8f853f65-1b29-41f9-9907-7259192f105b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""739b21b2-8c5c-4d07-8bb5-5b32b9793a88"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Click"",
                    ""action"": ""Mouse_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cf77e72-27eb-4a41-a483-ea56335efc92"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse_Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Click"",
            ""bindingGroup"": ""Click"",
            ""devices"": []
        }
    ]
}");
        // ClickAction
        m_ClickAction = asset.FindActionMap("ClickAction", throwIfNotFound: true);
        m_ClickAction_Mouse_Left = m_ClickAction.FindAction("Mouse_Left", throwIfNotFound: true);
        m_ClickAction_Mouse_Position = m_ClickAction.FindAction("Mouse_Position", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ClickAction
    private readonly InputActionMap m_ClickAction;
    private List<IClickActionActions> m_ClickActionActionsCallbackInterfaces = new List<IClickActionActions>();
    private readonly InputAction m_ClickAction_Mouse_Left;
    private readonly InputAction m_ClickAction_Mouse_Position;
    public struct ClickActionActions
    {
        private @ActionControl m_Wrapper;
        public ClickActionActions(@ActionControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @Mouse_Left => m_Wrapper.m_ClickAction_Mouse_Left;
        public InputAction @Mouse_Position => m_Wrapper.m_ClickAction_Mouse_Position;
        public InputActionMap Get() { return m_Wrapper.m_ClickAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ClickActionActions set) { return set.Get(); }
        public void AddCallbacks(IClickActionActions instance)
        {
            if (instance == null || m_Wrapper.m_ClickActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ClickActionActionsCallbackInterfaces.Add(instance);
            @Mouse_Left.started += instance.OnMouse_Left;
            @Mouse_Left.performed += instance.OnMouse_Left;
            @Mouse_Left.canceled += instance.OnMouse_Left;
            @Mouse_Position.started += instance.OnMouse_Position;
            @Mouse_Position.performed += instance.OnMouse_Position;
            @Mouse_Position.canceled += instance.OnMouse_Position;
        }

        private void UnregisterCallbacks(IClickActionActions instance)
        {
            @Mouse_Left.started -= instance.OnMouse_Left;
            @Mouse_Left.performed -= instance.OnMouse_Left;
            @Mouse_Left.canceled -= instance.OnMouse_Left;
            @Mouse_Position.started -= instance.OnMouse_Position;
            @Mouse_Position.performed -= instance.OnMouse_Position;
            @Mouse_Position.canceled -= instance.OnMouse_Position;
        }

        public void RemoveCallbacks(IClickActionActions instance)
        {
            if (m_Wrapper.m_ClickActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IClickActionActions instance)
        {
            foreach (var item in m_Wrapper.m_ClickActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ClickActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ClickActionActions @ClickAction => new ClickActionActions(this);
    private int m_ClickSchemeIndex = -1;
    public InputControlScheme ClickScheme
    {
        get
        {
            if (m_ClickSchemeIndex == -1) m_ClickSchemeIndex = asset.FindControlSchemeIndex("Click");
            return asset.controlSchemes[m_ClickSchemeIndex];
        }
    }
    public interface IClickActionActions
    {
        void OnMouse_Left(InputAction.CallbackContext context);
        void OnMouse_Position(InputAction.CallbackContext context);
    }
}
